### PR TITLE
ci(.github): add dispatch.yml

### PR DESCRIPTION
**Pull request by vdice**
* Add a dispatch workflow to send an event to a downstream repo when pushes to main occur

### CODE REVIEW

**Comment by mikkelhegn** [comment]
So this will enable us to automatically release an update of the www.fermyon.com when this repo changes?

**Comment by vdice** [comment]
@mikkelhegn yes -- or, specifically it will create a PR to bump the submodule commit for the www.fermyon.com website any time this repo gets a merge to `main`.

**Comment by mikkelhegn** [comment]
LGTM - @rajatjindal to review the GH actions workflow.

**Comment by vdice** [comment]
@rajatjindal if cycles allow, can you review this PR in tandem with https://github.com/fermyon/fermyon.com/pull/512 ?

**Review by rajatjindal — APPROVED** [review]

**Pull request merged**
